name: walking_tour_app
description: A walking tour app scaffold.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  flutter_map: ^6.1.1
  latlong2: ^0.9.0
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/manchester.svg
    - assets/tours.json
    # add audio assets here if you include local audio files
    # - assets/audio/intro.mp3
